In [13]:
from scipy import stats
import numpy as np
import pandas as pd

In [14]:
file_name = "../dataset/master_sheet.xlsx"
sheet_name = "Sheet1"

In [15]:
xl_sheet = pd.read_excel(file_name,sheet_name=sheet_name)

In [16]:
csv_path = "../dataset/master_sheet.csv"
xl_sheet.to_csv(csv_path, index=False)

In [17]:
df = pd.read_csv(csv_path)
df = df.iloc[:,:-16]
df.head()

,S.NO.,ID,Age,Sex,Presentation,Admission_Date,Admission Time,father,mother,firstdeg,...,OnD_Anticoagulant,OnD_INSULIN,OnD_Oral_Anti_glycemics,OnD_Non_statin_lipid_drugs,30 days Follow up Done Date,Method,Follow Up Status,Reinfarction,Hospitalization for Heart Failure,Stroke
0,1,DT01,45,Male,Direct,2021-07-29,14:10:00,No,No,No,...,No,No,No,No,2021-08-31,Telephonic,Alive,No,Yes,No
1,2,DT02,61,Male,Referral,2021-07-29,14:40:00,No,No,No,...,Yes,No,Yes,No,2021-08-31,Telephonic,Alive,No,No,No
2,3,DT03,45,Male,Referral,2021-07-28,17:10:00,No,No,No,...,No,No,Yes,No,2021-08-31,Telephonic,Deceased,No,No,No
3,4,DT04,50,Male,Referral,2021-07-29,14:20:00,No,No,No,...,Yes,No,No,No,2021-08-31,Telephonic,Alive,No,No,No
4,5,DT05,70,Female,Direct,2021-07-27,12:30:00,No,No,No,...,Yes,No,Yes,No,2021-08-31,Telephonic,Alive,No,No,No